apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: jenkins-pipeline-redconnect
    name: redconnect-pipeline
    template: application-template-sample-pipeline
  name: redconnect-pipeline
spec:
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('nodejs') {
          stage('build') {
            openshiftBuild(buildConfig: 'todo', showBuildLogs: 'true')
          }
          stage('deploy') {
            openshiftDeploy(deploymentConfig: 'todo')
          }
          stage( 'Wait for approval')
            input( 'Aprove to production?')
          stage('Deploy DEV-TEST'){
            openshiftDeploy(deploymentConfig: 'todo', namespace: 'todo-devtest')
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
